# Generated by Django 5.2.4 on 2025-07-04 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_media_file_post_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='post_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg', 'mp4', 'webm', 'avi'])], verbose_name='Медиа-контент'),
        ),
    ]
